#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

which etckeeper > /dev/null 2>&1 || exit 0

etckeeper commit "Saving uncommitted changes before puppet run"

# Failure of etckeeper should not be fatal.
exit 0
