#!/opt/puppetlabs/puppet/bin/ruby

# Run puppet in noop mode to see if there are any differences between
# the manifest and the current system config.

# This is intended to be run from cron so if any output is generated
# it will be emailed to root.

hostname=`/bin/hostname`.strip

command = '/opt/puppetlabs/bin/puppet apply '
command << '--show_diff --noop --color=false '
command << "/etc/puppetlabs/code/environments/production/manifests/site.pp "
command << '2>&1'

output = `#{command}`
abort("Error running puppet command: #{output}") unless $?.success?

# See if the command produced any useful output
diagnostics = []
output.split("\n").each do |line|
  next if line.empty? || line =~ /^Notice: (Compiled|Applied) catalog/
  diagnostics << line
end

if diagnostics.empty?
  exit(0)
else
  puts("puppet found differences between manifest and system on #{hostname}")
  puts()

  diagnostics.each { |line| puts line }
  exit(1)
end
